const char *server_introspection_xml =
	"<node>\n"

	"  <interface name='org.freedesktop.DBus.Introspectable'>\n"
	"    <method name='Introspect'>\n"
	"      <arg name='data' type='s' direction='out' />\n"
	"    </method>\n"
	"  </interface>\n"

	"  <interface name='org.freedesktop.DBus.Properties'>\n"
	"    <method name='Get'>\n"
	"      <arg name='interface' type='s' direction='in' />\n"
	"      <arg name='property'  type='s' direction='in' />\n"
	"      <arg name='value'     type='s' direction='out' />\n"
	"    </method>\n"
	"    <method name='GetAll'>\n"
	"      <arg name='interface'  type='s'     direction='in'/>\n"
	"      <arg name='properties' type='a{sv}' direction='out'/>\n"
	"    </method>\n"
	"  </interface>\n"

	"  <interface name='org.mpris.MediaPlayer2'>\n"
	"    <property name='CanQuit' type='b' access='read' />\n"
	"    <property name='Fullscreen' type='b' access='readwrite' />\n"
	"    <property name='CanSetFullscreen' type='b' access='read' />\n"
	"    <property name='CanRaise' type='b' access='read' />\n"
	"    <property name='HasTrackList' type='b' access='read' />\n"
	"    <property name='Identity' type='s' access='read' />\n"
	"    <property name='DesktopEntry' type='s' access='read' />\n"
	"    <property name='SupportedUriSchemes' type='as' access='read' />\n"
	"    <property name='SupportedMimeTypes' type='as' access='read' />\n"
	"    <method name='Raise' >\n"
	"    </method>\n"
	"    <method name='Quit'>\n"
	"    </method>\n"
	"  </interface>\n"

	"  <interface name='org.mpris.MediaPlayer2.Player'>\n"
	"    <property name='PlaybackStatus' type='s' access='read' />\n"
	"    <property name='LoopStatus' type='s' access='readwrite' />\n"
	"    <property name='Rate' type='d' access='readwrite' />\n"
	"    <property name='Shuffle' type='b' access='readwrite' />\n"
	"    <property name='Metadata' type='a{sv}' access='read' />\n"
	"    <property name='Volume' type='d' access='readwrite' />\n"
	"    <property name='Position' type='x' access='read' />\n"
	"    <property name='MinimumRate' type='d' access='read' />\n"
	"    <property name='MaximumRate' type='d' access='read' />\n"
	"    <property name='CanGoNext' type='b' access='read' />\n"
	"    <property name='CanGoPrevious' type='b' access='read' />\n"
	"    <property name='CanPlay' type='b' access='read' />\n"
	"    <property name='CanPause' type='b' access='read' />\n"
	"    <property name='CanSeek' type='b' access='read' />\n"
	"    <property name='CanControl' type='b' access='read' />\n"
	"    <method name='Play' >\n"
	"    </method>\n"
	"    <method name='Pause'>\n"
	"    </method>\n"
	"    <method name='Next'>\n"
	"    </method>\n"
	"    <method name='Previous'>\n"
	"    </method>\n"
	"    <method name='PlayPause'>\n"
	"    </method>\n"
	"    <method name='Stop'>\n"
	"    </method>\n"
	"    <method name='Seek'>\n"
	"		<arg name='Offset' type='x' direction='in'/>"
	"    </method>\n"
	"    <method name='SetPosition'>\n"
	"		<arg name='TrackId' type='o' direction='in'/>"
	"		<arg name='Position' type='x' direction='in'/>"
	"    </method>\n"
	"    <method name='OpenUri'>\n"
	"		<arg name='Uri' type='s' direction='in'/>"
	"    </method>\n"
	"  </interface>\n"

	"</node>\n";